/*
  extracts knowledge module properties for each mapping.
  data is sourced from the xml generated by the latest scenario.
  "phy_node_name" represents the node in the mapping's physical layer.
*/
with sss as (select * from snp_scen_step with read only)
,ss as (select * from snp_scen with read only)
,sp as (select * from snp_package with read only)
,step as (select * from snp_step with read only)
,sm as (select * from snp_mapping with read only)
,src0 as (
	select step.i_mapping as map_no
		,sss.gen_info as xml_clob
		,row_number() over (partition by sm.i_mapping order by ss.scen_no) rn
	from step
		inner join sp
			on step.i_package = sp.i_package
		inner join ss
			on sp.i_package = ss.i_package
		inner join sss
			on ss.scen_no = sss.scen_no
			and step.nno = sss.nno
		inner join sm
			on step.i_mapping = sm.i_mapping
	where 1=1
		and sss.gen_info is not null
		and step.step_type = 'M'
)
,src as (
	select
	    src.map_no
	    ,substr(n.node_km, 1, instr(n.node_km, '.')-1) as km_name
	    ,o.option_name as prop_name
	    ,n.node_name as phy_node_name
	    ,case
		  when o.option_value is null
		    or regexp_like(o.option_value, '^[[:space:]]*$')
		  then coalesce(o.option_value,'Unspecified')
		  else o.option_value
		end as prop_value
	from src0 src
		cross apply xmltable(
		    '/map-generation-info/node'
		    passing xmltype(src.xml_clob)
		    columns
		        node_pos  for ordinality,
		        node_xml  xmltype       path '.',
		        node_name varchar2(200) path '@name',
		        node_type varchar2(50)  path '@type',
		        node_km   varchar2(500) path '@km'
		) n
		outer apply xmltable(
		    '/node/option'
		    passing n.node_xml
		    columns
		        option_pos     for ordinality,
		        option_name    varchar2(200)  path '@name',
		        option_value   varchar2(4000) path '@value',
		        option_default varchar2(20)   path '@default'
		) o
	where src.rn = 1
		and case
		  when o.option_value is null
		    or regexp_like(o.option_value, '^[[:space:]]*$')
		  then 1
		  else 0
		end = 0
	order by
	    src.map_no
	    ,km_name
	    ,phy_node_name
)
select *
from src
;